# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-11-12 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20171112_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 23, 17, 42, 683784, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 12, 23, 17, 42, 682783, tzinfo=utc)),
        ),
    ]
